package me.valour.bowls.enums;

public enum Action {

	NONE, 
	ENTER_SUBTOTAL, EDIT_SUBTOTAL,
	ITEM_PRICE,
	CONFIRM_TAX, CONFIRM_TIP, 
	CHANGE_TAX, CHANGE_TIP,
	SET_TAX, SET_TIP, 
	SELECT_BOWLS,
	CONFIRM_DELETE;
}
